version: '1.0.{build}'
environment:
  NODE_ENV: production
  matrix:
    # node.js
    - nodejs_version: "4"
    - nodejs_version: "6"
    # io.js
    - nodejs_version: "1.0"

install:
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test