before_deploy:
- test $TRAVIS_TEST_RESULT = 0
after_success:
  - npm run build
  - firebase deploy --token ${FIREBASE_API_TOKEN}
branches:
  only:
  - master
env:
- NODE_ENV=production
install:
- npm install -g firebase-tools
- npm install
language: node_js
node_js:
- 6
script:
- npm test
#deploy:
 # provider: heroku
 # app: graphql-boilerplate
 # skip_cleanup: true
 # api_key:
 #   secure: ${HEROKU_API_KEY}
