language: node_js
node_js:
    - 6
    - 5
install:
    - npm install
# safelist
branches:
    only:
        - master
script:
    - npm test
    - npm lint
    - npm build
env:
    - NODE_ENV=production
before_deploy:
    - test $TRAVIS_TEST_RESULT = 0 \# check that build passed successfully
    && npm run build
