---
before_deploy:
  - "test $TRAVIS_TEST_RESULT = 0 && npm run build"
branches:
  only:
    - master
env:
  - NODE_ENV=production
install:
  - "npm install"
language: node_js
node_js:
  - 6
  - 5
script:
  - "npm test"
  - "npm lint"
  - "npm build"
