---
before_deploy:
  - "test $TRAVIS_TEST_RESULT = 0 && npm run build"
branches:
  only:
    - master
env:
  - NODE_ENV=production
install:
  - "npm install"
language: node_js
node_js:
  - 6
script:
  - "npm test"
  - "npm run build"
deploy:
  provider: heroku
  api_key:
    secure: "9ef27f06-5228-496f-9fc4-6db8d184f89d"
