before_deploy:
- test $TRAVIS_TEST_RESULT = 0 && npm run build
after_success:
  - firebase deploy --token=1/Kc2XVQI2p_Pbiq0fEwUFu5xPYCF6lePlQYzrgG0GWtBj3jaIbTtNlnfh0Z9No0ro
branches:
  only:
  - master
env:
- NODE_ENV=production
install:
- npm install -g firebase-tools
- npm install
language: node_js
node_js:
- 6
script:
- npm test
#deploy:
 # provider: heroku
 # app: graphql-boilerplate
 # skip_cleanup: true
 # api_key:
 #   secure: ${HEROKU_API_KEY}
